language: cpp

sudo: required
dist: trusty

services:
    - docker

matrix:
    include:
        - os: linux
          env: target=android-arm
        - os: linux
          env: target=android-arm64
        - os: linux
          env: target=linux-armv6
        - os: linux
          env: target=linux-arm64
        - os: linux
          env: target=linux-x86
        - os: linux
          env: target=linux-x64
        - os: linux
          env: target=windows-x86
        - os: linux
          env: target=windows-x64

script:
    - "scripts/ci/$target.sh"
